# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:     
  build:

    runs-on: ubuntu-latest
    container: node:lts
    services:
      postgres:
        
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres 
          
        options: >-
         --health-cmd pg_isready
                   
#     strategy:
#       matrix:
#         node-version: [10.x,12.x]

    steps:
    - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: node client.js
    - run: npm run build --if-present
    #- run: psql -U postgres
    - run: pg_isready  
    - run: npx sequelize-cli db:migrate
    - run: npm test
      env:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432  
        NODE_ENV: test
         
        CI: true
